# Generated by Django 5.0.3 on 2024-03-12 12:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0005_alter_author_date_of_birth_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 12, 12, 48, 17, 342020, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 12, 12, 48, 17, 342020, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='order_ht_product_ht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(max_length=8)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp2.order_ht')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp2.product_ht')),
            ],
        ),
    ]
