# Generated by Django 5.0.3 on 2024-03-20 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0008_product_ht_image_alter_author_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='shooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='photo/')),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 20, 16, 31, 43, 415377, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 20, 16, 31, 43, 416646, tzinfo=datetime.timezone.utc)),
        ),
    ]
