# Generated by Django 5.0.3 on 2024-03-20 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0010_alter_author_date_of_birth_alter_post_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shooter',
            old_name='photo',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 20, 18, 50, 19, 907820, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 20, 18, 50, 19, 908825, tzinfo=datetime.timezone.utc)),
        ),
    ]
